# -*- coding: utf-8 -*-
"""Types_of_encodings2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vftkVKC8C0nDRYfxkc5UJ-0pdfBgg9Pl

#TASK

A. Implementing Label encoding.
"""

import pandas as pd

from sklearn.preprocessing import LabelEncoder
 #C275
# Example labels
labels = ["correct", "negative", "neither","hehehehehe","correct"]
#C275
# Label Encoding
le = LabelEncoder()
encoded_labels = le.fit_transform(labels)#Transforms the words as a numerical val

print("Encoded Labels:", encoded_labels)

"""B. One hot encoding"""

from sklearn.preprocessing import OneHotEncoder
import numpy as np
labels = np.array(["correct", "negative", "neither","hehehehehe","correct"]).reshape(-1, 1)
# One Hot Encoding
ohe = OneHotEncoder()
one_hot_labels = ohe.fit_transform(labels)
#C275
print("One Hot Encoded Labels:\n", one_hot_labels)

"""c. Implementing BoW"""

from sklearn.feature_extraction.text import CountVectorizer
#C275
texts = ["The Moon is Earth's only natural satellite. It orbits around Earth at an average distance of 384399 km (238854 mi; about 30 times Earth's diameter). Its orbital period (lunar month) and its rotation period (lunar day) are synchronized at 29.5 days by Earth's gravity pulling on the Moon. This makes the Moon tidally locked to Earth, always facing it with the same side. The Moon's gravitational pull produces tidal forces on Earth, which are the main driver of Earth's tides."]
#C275
vectorizer = CountVectorizer()
bow = vectorizer.fit_transform(texts)#GIVING ALL THE WORDS A NUMERICAL VALUE

print("BoW Feature Names:", vectorizer.get_feature_names_out())
print("BoW Matrix:\n", bow)

"""d. Implementing TF-IDF"""

from sklearn.feature_extraction.text import TfidfVectorizer
texts = ["The Moon is Earth's only natural satellite. It orbits around Earth at an average distance of 384399 km (238854 mi; about 30 times Earth's diameter). Its orbital period (lunar month) and its rotation period (lunar day) are synchronized at 29.5 days by Earth's gravity pulling on the Moon. This makes the Moon tidally locked to Earth, always facing it with the same side. The Moon's gravitational pull produces tidal forces on Earth, which are the main driver of Earth's tides."]
#C275
# Change pattern to include 1-letter words (like "I")
vectorizer = TfidfVectorizer(token_pattern=r'\b\w+\b')
tfidf = vectorizer.fit_transform(texts)
#C275
print("Features:", vectorizer.get_feature_names_out())
print(tfidf.toarray())

"""e. Scikit learn to implement TFIDF"""

!pip install scikit-learn
#C275
from sklearn.feature_extraction.text import TfidfVectorizer
texts = ["The Moon is Earth's only natural satellite. It orbits around Earth at an average distance of 384399 km (238854 mi; about 30 times Earth's diameter). Its orbital period (lunar month) and its rotation period (lunar day) are synchronized at 29.5 days by Earth's gravity pulling on the Moon. This makes the Moon tidally locked to Earth, always facing it with the same side. The Moon's gravitational pull produces tidal forces on Earth, which are the main driver of Earth's tides."]
tfidf = TfidfVectorizer()
#C275
tfidf_matrix = tfidf.fit_transform(texts)

feature_names = tfidf.get_feature_names_out()
#C275
tfidf_array = tfidf_matrix.toarray()

print("Feature Names (Words):", feature_names)
print("\nTF-IDF Matrix:\n")
for i in range(len(texts)):
    print(f"Sentence {i+1}: {texts[i]}")
    for j in range(len(feature_names)):
        print(f"  {feature_names[j]}: {tfidf_array[i][j]:.4f}")
    print()

from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Create word cloud
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(local_text)

# Display the image
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title("Word Cloud of Document")
plt.show()